//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VincentRestorant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres_First
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Img { get; set; }
        public string Adres { get; set; }
        public string Clas { get; set; }
        public string Clas2 { get; set; }
        public string WorkingHouse { get; set; }
        public string WorkingTime { get; set; }
    }
}
