//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VincentRestorant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VincentRestourantEntities : DbContext
    {
        public VincentRestourantEntities()
            : base("name=VincentRestourantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Adres_First> Adres_First { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Ordersitem> Ordersitems { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSize> ProductSizes { get; set; }
        public virtual DbSet<Second_Slider> Second_Slider { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Sliderfirst> Sliderfirsts { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
