//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VincentRestorant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordersitem
    {
        public int ID { get; set; }
        public Nullable<int> Orders_ID { get; set; }
        public Nullable<int> Productsize_Id { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> Orderprice { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ProductSize ProductSize { get; set; }
    }
}
